#!/usr/bin/env python3
"""Regenerate proprietary-files.txt from an extracted stock partition tree.

Usage: gen-proprietary-files.py <extract-root> [-o proprietary-files.txt]

<extract-root> holds one directory per partition, e.g.
    <root>/vendor  <root>/vendor_dlkm  <root>/odm_dlkm  <root>/system_dlkm

Produces the LineageOS extract-utils blob list. Paths are emitted relative to
the partition root and prefixed with the partition name, which is the format
extract-files.py consumes.
"""
import argparse
import os

PARTITIONS = ('vendor', 'vendor_dlkm', 'odm_dlkm', 'system_dlkm')

# Files that are build artifacts / props rather than blobs to carry.
SKIP_NAMES = {'build.prop', 'ro.prop', 'rw.prop', 'default.prop', 'etc/fstab.mt6768'}

SECTIONS = (
    ('HAL services', lambda p: '/bin/hw/' in p),
    ('Executables', lambda p: '/bin/' in p),
    ('Trusted Applications (Microtrust/Beanpod TEE)', lambda p: '/thh/' in p),
    ('Kernel modules', lambda p: p.endswith('.ko')),
    ('Firmware', lambda p: '/firmware/' in p),
    ('64-bit libraries', lambda p: '/lib64/' in p),
    ('32-bit libraries', lambda p: '/lib/' in p),
    ('APKs and JARs', lambda p: p.endswith(('.apk', '.jar'))),
    ('Configuration, init and VINTF', lambda p: p.endswith(('.xml', '.rc', '.conf', '.json', '.txt', '.cfg'))),
)


def collect(root):
    blobs = []
    for part in PARTITIONS:
        base = os.path.join(root, part)
        if not os.path.isdir(base):
            continue
        for dirpath, _dirnames, filenames in os.walk(base):
            for name in filenames:
                full = os.path.join(dirpath, name)
                if os.path.islink(full):
                    continue
                rel = os.path.relpath(full, base)
                if rel in SKIP_NAMES or name in SKIP_NAMES:
                    continue
                blobs.append(f'{part}/{rel}')
    return sorted(set(blobs))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('root')
    ap.add_argument('-o', '--output', default='proprietary-files.txt')
    args = ap.parse_args()

    blobs = collect(args.root)
    remaining = list(blobs)
    out = [
        '# Proprietary blobs for Lenovo TB305FU / clove_row_wifi (LineageOS 22.2).',
        '#',
        '# Generated by gen-proprietary-files.py from the stock Android 15 partitions',
        '# pulled live over adb from the merged Virtual A/B mapper devices',
        '# (/dev/block/mapper/{vendor,vendor_dlkm,odm_dlkm,system_dlkm}_a, slot A).',
        '#',
        '# Do NOT regenerate this from an lpunpack of super.bin: that yields the',
        '# pre-snapshot BASE image, whose COW-updated inodes are zeroed, and',
        '# /vendor/etc and /vendor/firmware come out unreadable.',
        '#',
        f'# {len(blobs)} blobs.',
        '',
    ]
    for title, match in SECTIONS:
        picked = [b for b in remaining if match(b)]
        if not picked:
            continue
        remaining = [b for b in remaining if b not in set(picked)]
        out.append(f'## {title}')
        out.extend(picked)
        out.append('')
    if remaining:
        out.append('## Other')
        out.extend(remaining)
        out.append('')

    with open(args.output, 'w') as fh:
        fh.write('\n'.join(out))
    print(f'{len(blobs)} blobs -> {args.output}')


if __name__ == '__main__':
    main()
